name: 🌐 Channel Request
description: Suggest a new source
body:

  - type: input
    id: name
    attributes:
      label: Channel Name
      placeholder: |
        Example: "Example NDTV"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Source Link
      placeholder: |
        Example: "https://youtube.com/example"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Language
      placeholder: |
        Example: "English"
    validations:
      required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: I have checked that the source does not already exist.
          required: true
